### ISSUE TITLE
Skip file - is that like a dump button?

### ISSUE THREAD

**Issue by redimongo** [daansystems/radiodelay#1]
So we are looking for away to introduce a LIVE dump audio button for online radio. We currently have no way to take our audio from our station and prevent callers swearing etc live on radio. We are wondering if this skip file allows us to put a 7 second audio clip and when a host hits skip that it dumps the sound from the input and replaces it with the 7 second clip?

Looking forward to your reply also can you program the skip button to work with  a stream Deck?

**Comment by daansystems** [comment]
That is what it can be used for. About Stream Deck I'm not sure, perhaps you can make a plugin that "clicks" the skip button?

**Comment by daansystems** [comment]
closing the issue
