### ISSUE TITLE
Shortcut to skip audio

### ISSUE THREAD

**Issue by redimongo** [daansystems/radiodelay#6]
I am wondering if there is a F11 or away to set a key to skip the audio. Ideally we would like to use this with our stream deck?

**Comment by daansystems** [comment]
Please check the latest version, there are now shortcuts available for play/stop/skip

**Comment by redimongo** [comment]
Ok if there is no shortcuts I am wanting to know what software did you use to make this - I know it is a C app.
and I believe I know what part of the code I would need to charge, I would need to put a F7 button command to press the button skip.

It sounds easy. but I am not 100% sure - as I have never done a C app. but if I can figure it out I would be happy to share the code back.

**Comment by daansystems** [comment]
Sorry, the latest version does have shortcuts now (F5/F6), i mistyped "now" for "not" (fixed)
